# base image
#FROM python:3.9
FROM woahbase/alpine-rpigpio:armhf
# update the container os
#RUN apt-get update && apt-get install -y --no-install-recommends \
#    python3.9 \
#    python3-pip \
#    && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/*
#RUN apk add --update --no-cache --virtual .tmp gcc libc-dev linux-headers
#RUN apt-get -y update && apt-get install -y gcc libzbar-dev
#RUN python -m pip install --upgrade pip
# add python libraries
RUN pip install RPi.GPIO paho-mqtt pyserial
# labels
LABEL Maintainer='dbusa'

# set working directory of container
WORKDIR /usr/app/src

# copy remote file to container
COPY control.py ./

# CMD instruction to run python script
CMD ["python", "./control.py"]
